
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 01 16:35:58 BRST 2010
//----------------------------------------------------

package runtime;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SQRT = 52;
  public static final int MULT = 12;
  public static final int SQR = 53;
  public static final int CONST = 42;
  public static final int OPAR = 14;
  public static final int OCOL = 7;
  public static final int ELSIF = 21;
  public static final int DIFERENTE = 36;
  public static final int CPAR = 15;
  public static final int CCOL = 8;
  public static final int INTEGER = 6;
  public static final int REPEAT = 24;
  public static final int ARRAY = 45;
  public static final int MAIORIGUAL = 35;
  public static final int WRITE = 48;
  public static final int VIRGULA = 13;
  public static final int PONTO = 10;
  public static final int AND = 37;
  public static final int NOT = 29;
  public static final int MENORIGUAL = 34;
  public static final int IGUAL = 28;
  public static final int OR = 38;
  public static final int MAIS = 26;
  public static final int BEGIN = 40;
  public static final int DIV = 30;
  public static final int UNTIL = 25;
  public static final int NUM = 2;
  public static final int WRITELN = 49;
  public static final int IF = 18;
  public static final int ID = 9;
  public static final int OF = 44;
  public static final int EOF = 0;
  public static final int BOOLEAN = 5;
  public static final int MAIOR = 33;
  public static final int SIZE = 47;
  public static final int TRUE = 3;
  public static final int error = 1;
  public static final int MENOS = 27;
  public static final int MENOR = 32;
  public static final int MOD = 31;
  public static final int READLN = 51;
  public static final int MODULE = 39;
  public static final int ATRIB = 16;
  public static final int ELSE = 19;
  public static final int READ = 50;
  public static final int WHILE = 23;
  public static final int THEN = 20;
  public static final int END = 41;
  public static final int FALSE = 4;
  public static final int PTVIRGULA = 11;
  public static final int PROCEDURE = 46;
  public static final int VAR = 43;
  public static final int DO = 22;
  public static final int DOISPONTOS = 17;
}

